### ISSUE TITLE
Newt-serif weights do not share the same family name

### ISSUE THREAD

**Issue by demoy** [chuckmasterson/newt-serif#1]
The "Family Name" for each weight is different resulting in each being treat a a separate family: a side-effect of this being application using faux bold, instead of the existing bold weight.
![Font Name information in Fontforge](https://cloud.githubusercontent.com/assets/2396524/25634778/73e72dd2-2f41-11e7-96fa-d1f91392ea7e.png)

Thanks in advance.

**Comment by chuckmasterson** [comment]
I originally did this at the request of my first reseller. They pointed out that since this family has four weights, a lot of people would only be able to access two of the weights from their applications—Word, for example, only gives you "normal" and "bold".

So I split each weight out into its own font. This is, I suppose, not an ideal solution for the reason you're pointing out (faux bold). Do you think a better solution would be to combine Regular + Demi into one font, and Light + Bold into a second font? If we combine them all into one, I don't know how Windows users will be able to actually use half the family, but if you have insight on that it's welcome.

**Comment by demoy** [comment]
It fine if its intentional. Many CSS workaround already exist for me.
